before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test ./...
builds:
  - env:
      - CGO_ENABLED=0
    main: cmd/main.go
    goos:
      - linux
    ldflags:
      - -s -w -X github.com/streamdp/ip-info/config.Version={{.Version}}
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Tag }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE
      - pkg/ratelimiter/REDIS-RATE-LICENSE
      - pkg/redis_client/REDIS-LICENSE
      - database/model/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
