version: "3.4"
services:
   postgres:
      image: postgres:16.4-alpine
      ports:
         -  "5432:5432"
      environment:
         - POSTGRES_DB=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
      volumes:
         - ../postgres/ip-info/postgres_data:/var/lib/postgresql/data
         - ./database/model:/docker-entrypoint-initdb.d/:ro
      container_name: postgres
      restart: always

   ip-info:
      build: .
      image: streamdp/ip-info:v0.4.6
      environment:
         - IP_INFO_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/dbip?sslmode=disable
         - IP_INFO_ENABLE_LIMITER=true
         - IP_INFO_RATE_LIMIT=15
      ports:
         - "8080:8080"
         - "50051:50051"
      container_name: ip-info
      healthcheck:
         test: ["CMD", "wget", "--spider", "http://ip-info:8080/healthz"]
         interval: 30s
         retries: 5
         start_period: 15s
         timeout: 10s
      restart: always
      depends_on:
         - postgres
