// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/ip_info.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IpInfo_GetIpInfo_FullMethodName = "/IpInfo/GetIpInfo"
)

// IpInfoClient is the client API for IpInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IpInfoClient interface {
	GetIpInfo(ctx context.Context, in *Ip, opts ...grpc.CallOption) (*Response, error)
}

type ipInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewIpInfoClient(cc grpc.ClientConnInterface) IpInfoClient {
	return &ipInfoClient{cc}
}

func (c *ipInfoClient) GetIpInfo(ctx context.Context, in *Ip, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, IpInfo_GetIpInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IpInfoServer is the server API for IpInfo service.
// All implementations must embed UnimplementedIpInfoServer
// for forward compatibility.
type IpInfoServer interface {
	GetIpInfo(context.Context, *Ip) (*Response, error)
	mustEmbedUnimplementedIpInfoServer()
}

// UnimplementedIpInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIpInfoServer struct{}

func (UnimplementedIpInfoServer) GetIpInfo(context.Context, *Ip) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIpInfo not implemented")
}
func (UnimplementedIpInfoServer) mustEmbedUnimplementedIpInfoServer() {}
func (UnimplementedIpInfoServer) testEmbeddedByValue()                {}

// UnsafeIpInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IpInfoServer will
// result in compilation errors.
type UnsafeIpInfoServer interface {
	mustEmbedUnimplementedIpInfoServer()
}

func RegisterIpInfoServer(s grpc.ServiceRegistrar, srv IpInfoServer) {
	// If the following call pancis, it indicates UnimplementedIpInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IpInfo_ServiceDesc, srv)
}

func _IpInfo_GetIpInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpInfoServer).GetIpInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IpInfo_GetIpInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpInfoServer).GetIpInfo(ctx, req.(*Ip))
	}
	return interceptor(ctx, in, info, handler)
}

// IpInfo_ServiceDesc is the grpc.ServiceDesc for IpInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IpInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "IpInfo",
	HandlerType: (*IpInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIpInfo",
			Handler:    _IpInfo_GetIpInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ip_info.proto",
}
